[2024-11-28T02:38:12.066+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-28T02:38:12.077+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-28T02:37:57.744343+00:00 [queued]>
[2024-11-28T02:38:12.083+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-28T02:37:57.744343+00:00 [queued]>
[2024-11-28T02:38:12.083+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-28T02:38:12.092+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_bronze> on 2024-11-28 02:37:57.744343+00:00
[2024-11-28T02:38:12.095+0000] {standard_task_runner.py:72} INFO - Started process 68 to run task
[2024-11-28T02:38:12.098+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'brewery_bronze_layer', 'load_bronze', 'manual__2024-11-28T02:37:57.744343+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/openbrewery_dag.py', '--cfg-path', '/tmp/tmp5ogm0t8n']
[2024-11-28T02:38:12.100+0000] {standard_task_runner.py:105} INFO - Job 59: Subtask load_bronze
[2024-11-28T02:38:12.134+0000] {task_command.py:467} INFO - Running <TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-28T02:37:57.744343+00:00 [running]> on host a8d38ebdeb14
[2024-11-28T02:38:12.190+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='brewery_bronze_layer' AIRFLOW_CTX_TASK_ID='load_bronze' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T02:37:57.744343+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-28T02:37:57.744343+00:00'
[2024-11-28T02:38:12.190+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-28T02:38:12.200+0000] {load_bronze_module.py:88} INFO - Iniciando a tarefa load_bronze
[2024-11-28T02:38:12.343+0000] {load_bronze_module.py:98} INFO - Recebidos 8355 registros para carregar na camada Bronze
[2024-11-28T02:38:12.343+0000] {load_bronze_module.py:62} ERROR - Erro ao criar sess√£o Spark: name 'os' is not defined
[2024-11-28T02:38:12.343+0000] {load_bronze_module.py:144} ERROR - Erro ao salvar dados na camada Bronze: name 'os' is not defined
[2024-11-28T02:38:12.344+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/scripts/load_bronze_module.py", line 101, in load_bronze
    spark = create_spark_session()
  File "/opt/airflow/scripts/load_bronze_module.py", line 42, in create_spark_session
    aws_access_key = os.getenv("AWS_ACCESS_KEY_ID")
NameError: name 'os' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/scripts/load_bronze_module.py", line 147, in load_bronze
    spark.stop()
UnboundLocalError: local variable 'spark' referenced before assignment
[2024-11-28T02:38:12.354+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=brewery_bronze_layer, task_id=load_bronze, run_id=manual__2024-11-28T02:37:57.744343+00:00, execution_date=20241128T023757, start_date=20241128T023812, end_date=20241128T023812
[2024-11-28T02:38:12.365+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-28T02:38:12.366+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 59 for task load_bronze (local variable 'spark' referenced before assignment; 68)
Traceback (most recent call last):
  File "/opt/airflow/scripts/load_bronze_module.py", line 101, in load_bronze
    spark = create_spark_session()
  File "/opt/airflow/scripts/load_bronze_module.py", line 42, in create_spark_session
    aws_access_key = os.getenv("AWS_ACCESS_KEY_ID")
NameError: name 'os' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/scripts/load_bronze_module.py", line 147, in load_bronze
    spark.stop()
UnboundLocalError: local variable 'spark' referenced before assignment
[2024-11-28T02:38:12.391+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-28T02:38:12.409+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-28T02:38:12.411+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
