[2024-11-28T20:32:22.096+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-28T20:32:22.109+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: brewery_ETL.transform_silver manual__2024-11-28T20:29:14.545680+00:00 [queued]>
[2024-11-28T20:32:22.114+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: brewery_ETL.transform_silver manual__2024-11-28T20:29:14.545680+00:00 [queued]>
[2024-11-28T20:32:22.115+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-28T20:32:22.125+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform_silver> on 2024-11-28 20:29:14.545680+00:00
[2024-11-28T20:32:22.130+0000] {standard_task_runner.py:72} INFO - Started process 766 to run task
[2024-11-28T20:32:22.133+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'brewery_ETL', 'transform_silver', 'manual__2024-11-28T20:29:14.545680+00:00', '--job-id', '175', '--raw', '--subdir', 'DAGS_FOLDER/openbrewery_dag.py', '--cfg-path', '/tmp/tmpxim3y0y9']
[2024-11-28T20:32:22.135+0000] {standard_task_runner.py:105} INFO - Job 175: Subtask transform_silver
[2024-11-28T20:32:22.175+0000] {task_command.py:467} INFO - Running <TaskInstance: brewery_ETL.transform_silver manual__2024-11-28T20:29:14.545680+00:00 [running]> on host 0bec9c1b1e07
[2024-11-28T20:32:22.248+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='brewery_ETL' AIRFLOW_CTX_TASK_ID='transform_silver' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T20:29:14.545680+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-28T20:29:14.545680+00:00'
[2024-11-28T20:32:22.249+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-28T20:32:22.270+0000] {transform_silver.py:112} INFO - Iniciando a tarefa transform_silver
[2024-11-28T20:32:22.271+0000] {transform_silver.py:126} INFO - Data de execução: 2024-11-28
[2024-11-28T20:32:22.271+0000] {transform_silver.py:16} INFO - Iniciando criação da sessão Spark para transformação Silver
[2024-11-28T20:32:29.764+0000] {transform_silver.py:40} INFO - Sessão Spark criada com sucesso para transformação Silver
[2024-11-28T20:32:29.764+0000] {transform_silver.py:49} INFO - Lendo dados da camada Bronze: s3a://breweris-etl-prod-sp/bronze/date=2024-11-28
[2024-11-28T20:32:45.546+0000] {job.py:229} INFO - Heartbeat recovered after 13.31 seconds
[2024-11-28T20:32:46.660+0000] {transform_silver.py:52} INFO - Dados da camada Bronze carregados: 8355 registros
[2024-11-28T20:32:46.660+0000] {transform_silver.py:61} INFO - Iniciando transformações na camada Silver
[2024-11-28T20:32:48.272+0000] {transform_silver.py:66} INFO - Duplicatas removidas. Total de registros: 8355
[2024-11-28T20:32:48.413+0000] {transform_silver.py:82} INFO - Coluna 'localizacao' adicionada ao DataFrame
[2024-11-28T20:32:48.413+0000] {transform_silver.py:86} INFO - Tipos de dados convertidos com sucesso e coluna 'localizacao' garantida
[2024-11-28T20:32:48.413+0000] {transform_silver.py:88} INFO - Transformações na camada Silver concluídas
[2024-11-28T20:32:48.425+0000] {transform_silver.py:140} INFO - Schema do DataFrame após transformações na camada Silver:
[2024-11-28T20:32:48.427+0000] {logging_mixin.py:190} INFO - root
 |-- id: string (nullable = true)
 |-- name: string (nullable = true)
 |-- brewery_type: string (nullable = true)
 |-- street: string (nullable = true)
 |-- city: string (nullable = true)
 |-- state: string (nullable = true)
 |-- postal_code: string (nullable = true)
 |-- country: string (nullable = true)
 |-- longitude: float (nullable = true)
 |-- latitude: float (nullable = true)
 |-- phone: string (nullable = true)
 |-- website_url: string (nullable = true)
 |-- updated_at: string (nullable = true)
 |-- tag_list: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- localizacao: string (nullable = false)
 |-- date: string (nullable = false)
[2024-11-28T20:32:48.427+0000] {transform_silver.py:97} INFO - Escrevendo dados na camada Silver: s3a://breweris-etl-prod-sp/silver/date=2024-11-28
[2024-11-28T20:32:50.607+0000] {job.py:229} INFO - Heartbeat recovered after 10.61 seconds
[2024-11-28T20:40:51.924+0000] {job.py:229} INFO - Heartbeat recovered after 186.26 seconds
[2024-11-28T20:41:06.012+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2024-11-28T20:41:06.015+0000] {process_utils.py:132} INFO - Sending 15 to group 766. PIDs of all processes in the group: [768, 766]
[2024-11-28T20:41:06.015+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 766
[2024-11-28T20:41:06.015+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-28T20:41:06.501+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/opt/airflow/scripts/transform_silver.py", line 144, in transform_silver
    write_silver_data(df_silver, spark, s3_bucket, s3_silver_path, execution_date)
  File "/opt/airflow/scripts/transform_silver.py", line 102, in write_silver_data
    df.write.mode('overwrite') \
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/readwriter.py", line 1656, in parquet
    self._jwrite.parquet(path)
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1321, in __call__
    answer = self.gateway_client.send_command(command)
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.9/socket.py", line 716, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.9/socket.py", line 716, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[2024-11-28T20:41:06.506+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.506+0000] {java_gateway.py:1055} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/opt/airflow/scripts/transform_silver.py", line 144, in transform_silver
    write_silver_data(df_silver, spark, s3_bucket, s3_silver_path, execution_date)
  File "/opt/airflow/scripts/transform_silver.py", line 102, in write_silver_data
    df.write.mode('overwrite') \
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/readwriter.py", line 1656, in parquet
    self._jwrite.parquet(path)
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1321, in __call__
    answer = self.gateway_client.send_command(command)
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.9/socket.py", line 716, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.9/socket.py", line 716, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/clientserver.py", line 539, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2024-11-28T20:41:06.509+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.9/site-packages/pyspark/context.py:654 RuntimeWarning: Unable to cleanly shutdown Spark JVM process. It is possible that the process has crashed, been killed or may also be in a zombie state.
[2024-11-28T20:41:06.922+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/clientserver.py", line 516, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty
[2024-11-28T20:41:06.923+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.923+0000] {java_gateway.py:1055} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/clientserver.py", line 516, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/clientserver.py", line 539, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2024-11-28T20:41:06.923+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.923+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.924+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.924+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.924+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.924+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.924+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.925+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.925+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.925+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.925+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.925+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.925+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.926+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.926+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.926+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.926+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.926+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.926+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.927+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.927+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.927+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.927+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.927+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.928+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.928+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.928+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.928+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.928+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.928+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.929+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.929+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.929+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.929+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.929+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.929+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.930+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.930+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.930+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.930+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.930+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.930+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.931+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.931+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.931+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.931+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.931+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.931+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.932+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.932+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.932+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.932+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.932+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.933+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.933+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.933+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.933+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.933+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.933+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.934+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.934+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.934+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.934+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.934+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.934+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.935+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.935+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.935+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.935+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.935+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.935+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.936+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.936+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.936+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.936+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.936+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.936+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.937+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.937+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.937+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.937+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.937+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.937+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.964+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-11-28T20:41:06.965+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/scripts/transform_silver.py", line 144, in transform_silver
    write_silver_data(df_silver, spark, s3_bucket, s3_silver_path, execution_date)
  File "/opt/airflow/scripts/transform_silver.py", line 102, in write_silver_data
    df.write.mode('overwrite') \
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/readwriter.py", line 1656, in parquet
    self._jwrite.parquet(path)
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1321, in __call__
    answer = self.gateway_client.send_command(command)
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.9/socket.py", line 716, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/scripts/transform_silver.py", line 152, in transform_silver
    spark.stop()
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/session.py", line 1602, in stop
    self._jvm.SparkSession.clearDefaultSession()
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1712, in __getattr__
    answer = self._gateway_client.send_command(
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1036, in send_command
    connection = self._get_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/clientserver.py", line 284, in _get_connection
    connection = self._create_new_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/clientserver.py", line 291, in _create_new_connection
    connection.connect_to_java_server()
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/clientserver.py", line 438, in connect_to_java_server
    self.socket.connect((self.java_address, self.java_port))
ConnectionRefusedError: [Errno 111] Connection refused
[2024-11-28T20:41:06.980+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=brewery_ETL, task_id=transform_silver, run_id=manual__2024-11-28T20:29:14.545680+00:00, execution_date=20241128T202914, start_date=20241128T203222, end_date=20241128T204106
[2024-11-28T20:41:07.001+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-28T20:41:07.001+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 175 for task transform_silver ([Errno 111] Connection refused; 766)
Traceback (most recent call last):
  File "/opt/airflow/scripts/transform_silver.py", line 144, in transform_silver
    write_silver_data(df_silver, spark, s3_bucket, s3_silver_path, execution_date)
  File "/opt/airflow/scripts/transform_silver.py", line 102, in write_silver_data
    df.write.mode('overwrite') \
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/readwriter.py", line 1656, in parquet
    self._jwrite.parquet(path)
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1321, in __call__
    answer = self.gateway_client.send_command(command)
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.9/socket.py", line 716, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/scripts/transform_silver.py", line 152, in transform_silver
    spark.stop()
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/session.py", line 1602, in stop
    self._jvm.SparkSession.clearDefaultSession()
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1712, in __getattr__
    answer = self._gateway_client.send_command(
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1036, in send_command
    connection = self._get_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/clientserver.py", line 284, in _get_connection
    connection = self._create_new_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/clientserver.py", line 291, in _create_new_connection
    connection.connect_to_java_server()
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/clientserver.py", line 438, in connect_to_java_server
    self.socket.connect((self.java_address, self.java_port))
ConnectionRefusedError: [Errno 111] Connection refused
[2024-11-28T20:41:07.041+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=766, status='terminated', exitcode=1, started='20:32:21') (766) terminated with exit code 1
[2024-11-28T20:41:07.042+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=768, status='terminated', started='20:32:21') (768) terminated with exit code None
[2024-11-28T20:41:07.042+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 143
[2024-11-28T20:41:07.054+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
