[2024-11-28T03:51:27.338+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-28T03:51:27.359+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-28T03:37:01.347786+00:00 [queued]>
[2024-11-28T03:51:27.369+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-28T03:37:01.347786+00:00 [queued]>
[2024-11-28T03:51:27.369+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-28T03:51:27.384+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_bronze> on 2024-11-28 03:37:01.347786+00:00
[2024-11-28T03:51:27.387+0000] {standard_task_runner.py:72} INFO - Started process 64 to run task
[2024-11-28T03:51:27.391+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'brewery_bronze_layer', 'load_bronze', 'manual__2024-11-28T03:37:01.347786+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/openbrewery_dag.py', '--cfg-path', '/tmp/tmpaqwp_stm']
[2024-11-28T03:51:27.393+0000] {standard_task_runner.py:105} INFO - Job 109: Subtask load_bronze
[2024-11-28T03:51:27.441+0000] {task_command.py:467} INFO - Running <TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-28T03:37:01.347786+00:00 [running]> on host e4d8275f6fbb
[2024-11-28T03:51:27.512+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='brewery_bronze_layer' AIRFLOW_CTX_TASK_ID='load_bronze' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T03:37:01.347786+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-28T03:37:01.347786+00:00'
[2024-11-28T03:51:27.513+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-28T03:51:27.525+0000] {load_bronze_module.py:109} INFO - Iniciando a tarefa load_bronze
[2024-11-28T03:51:27.539+0000] {load_bronze_module.py:117} ERROR - Variáveis S3_BUCKET ou S3_BRONZE_PATH não estão definidas.
[2024-11-28T03:51:27.540+0000] {load_bronze_module.py:185} ERROR - Erro ao salvar dados na camada Bronze: Variáveis S3_BUCKET ou S3_BRONZE_PATH não estão definidas.
[2024-11-28T03:51:27.541+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/scripts/load_bronze_module.py", line 118, in load_bronze
    raise ValueError("Variáveis S3_BUCKET ou S3_BRONZE_PATH não estão definidas.")
ValueError: Variáveis S3_BUCKET ou S3_BRONZE_PATH não estão definidas.
[2024-11-28T03:51:27.548+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=brewery_bronze_layer, task_id=load_bronze, run_id=manual__2024-11-28T03:37:01.347786+00:00, execution_date=20241128T033701, start_date=20241128T035127, end_date=20241128T035127
[2024-11-28T03:51:27.560+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-28T03:51:27.561+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 109 for task load_bronze (Variáveis S3_BUCKET ou S3_BRONZE_PATH não estão definidas.; 64)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/scripts/load_bronze_module.py", line 118, in load_bronze
    raise ValueError("Variáveis S3_BUCKET ou S3_BRONZE_PATH não estão definidas.")
ValueError: Variáveis S3_BUCKET ou S3_BRONZE_PATH não estão definidas.
[2024-11-28T03:51:27.604+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-28T03:51:27.619+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-28T03:51:27.621+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
