[2024-11-28T03:37:18.630+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-28T03:37:18.655+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-28T03:37:01.347786+00:00 [queued]>
[2024-11-28T03:37:18.664+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-28T03:37:01.347786+00:00 [queued]>
[2024-11-28T03:37:18.664+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-28T03:37:18.683+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_bronze> on 2024-11-28 03:37:01.347786+00:00
[2024-11-28T03:37:18.688+0000] {standard_task_runner.py:72} INFO - Started process 63 to run task
[2024-11-28T03:37:18.692+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'brewery_bronze_layer', 'load_bronze', 'manual__2024-11-28T03:37:01.347786+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/openbrewery_dag.py', '--cfg-path', '/tmp/tmpi_1z1n6m']
[2024-11-28T03:37:18.694+0000] {standard_task_runner.py:105} INFO - Job 105: Subtask load_bronze
[2024-11-28T03:37:18.747+0000] {task_command.py:467} INFO - Running <TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-28T03:37:01.347786+00:00 [running]> on host 369c7674d54c
[2024-11-28T03:37:18.842+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='brewery_bronze_layer' AIRFLOW_CTX_TASK_ID='load_bronze' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T03:37:01.347786+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-28T03:37:01.347786+00:00'
[2024-11-28T03:37:18.843+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-28T03:37:18.855+0000] {load_bronze_module.py:112} INFO - Iniciando a tarefa load_bronze
[2024-11-28T03:37:19.010+0000] {load_bronze_module.py:123} INFO - Recebidos 8355 registros para carregar na camada Bronze
[2024-11-28T03:46:20.190+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2024-11-28T03:46:20.192+0000] {process_utils.py:132} INFO - Sending 15 to group 63. PIDs of all processes in the group: [65, 63]
[2024-11-28T03:46:20.193+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 63
[2024-11-28T03:46:20.194+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-28T03:46:20.206+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/scripts/load_bronze_module.py", line 126, in load_bronze
    return  # Não levantar exceção para não falhar a DAG
  File "/opt/airflow/scripts/load_bronze_module.py", line 59, in create_spark_session
    .config("spark.hadoop.fs.s3a.access.key", aws_access_key) \
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/session.py", line 477, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/context.py", line 512, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/context.py", line 198, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/context.py", line 432, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/java_gateway.py", line 103, in launch_gateway
    time.sleep(0.1)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-11-28T03:46:20.213+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=brewery_bronze_layer, task_id=load_bronze, run_id=manual__2024-11-28T03:37:01.347786+00:00, execution_date=20241128T033701, start_date=20241128T033718, end_date=20241128T034620
[2024-11-28T03:46:20.225+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-28T03:46:20.245+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=63, status='terminated', exitcode=2, started='03:37:18') (63) terminated with exit code 2
[2024-11-28T03:46:20.246+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=65, status='terminated', started='03:37:18') (65) terminated with exit code None
[2024-11-28T03:46:20.246+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 143
[2024-11-28T03:46:20.257+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
