[2024-11-27T04:36:45.360+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-27T04:31:28.636933+00:00 [queued]>
[2024-11-27T04:36:45.373+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-27T04:31:28.636933+00:00 [queued]>
[2024-11-27T04:36:45.373+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2024-11-27T04:36:45.394+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_bronze> on 2024-11-27 04:31:28.636933+00:00
[2024-11-27T04:36:45.402+0000] {standard_task_runner.py:57} INFO - Started process 511 to run task
[2024-11-27T04:36:45.406+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'brewery_bronze_layer', 'load_bronze', 'manual__2024-11-27T04:31:28.636933+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/openbrewery_dag.py', '--cfg-path', '/tmp/tmpljn64a0o']
[2024-11-27T04:36:45.410+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask load_bronze
[2024-11-27T04:36:45.474+0000] {task_command.py:415} INFO - Running <TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-27T04:31:28.636933+00:00 [running]> on host c559e0f5374b
[2024-11-27T04:36:45.570+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='brewery_bronze_layer' AIRFLOW_CTX_TASK_ID='load_bronze' AIRFLOW_CTX_EXECUTION_DATE='2024-11-27T04:31:28.636933+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-27T04:31:28.636933+00:00'
[2024-11-27T04:36:45.571+0000] {load_bronze_module.py:73} INFO - Iniciando a tarefa load_bronze
[2024-11-27T04:36:45.714+0000] {load_bronze_module.py:82} INFO - Recebidos 8355 registros para carregar na camada Bronze
[2024-11-27T04:36:45.714+0000] {load_bronze_module.py:40} INFO - Criando sess√£o Spark
[2024-11-27T04:36:45.723+0000] {load_bronze_module.py:128} ERROR - Erro ao salvar dados na camada Bronze: 'Variable AWS_ACCESS_KEY_ID does not exist'
[2024-11-27T04:36:45.724+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/scripts/load_bronze_module.py", line 85, in load_bronze
    spark = create_spark_session()
  File "/opt/airflow/scripts/load_bronze_module.py", line 43, in create_spark_session
    .config("spark.hadoop.fs.s3a.access.key", Variable.get("AWS_ACCESS_KEY_ID")) \
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable AWS_ACCESS_KEY_ID does not exist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/load_bronze_module.py", line 131, in load_bronze
    spark.stop()
UnboundLocalError: local variable 'spark' referenced before assignment
[2024-11-27T04:36:45.733+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=brewery_bronze_layer, task_id=load_bronze, execution_date=20241127T043128, start_date=20241127T043645, end_date=20241127T043645
[2024-11-27T04:36:45.744+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 36 for task load_bronze (local variable 'spark' referenced before assignment; 511)
[2024-11-27T04:36:45.780+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-27T04:36:45.798+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
